---

# web
- hosts: web
  become: yes
  vars:
    # https://github.com/jweissig/episode-47/releases
    app_version: release-0.02
  serial: 1

  pre_tasks:
  - name: disable server in haproxy
    shell: echo "disable server episode46/{{ inventory_hostname }}" | socat stdio /var/lib/haproxy/stats
    delegate_to: "{{ item }}"
    with_items: groups.lb

  roles:
    - roll

  post_tasks:
  - name: enable server in haproxy
    shell: echo "enable server episode46/{{ inventory_hostname }}" | socat stdio /var/lib/haproxy/stats
    delegate_to: "{{ item }}"
    with_items: groups.lb
